from ConfigException import ConfigException

class HAConf:
    """Object representation of the config file.
    
    Contains all the paramaters of the application.
    Generated by the HAConfigParser.loadConf() (see HAConfigParser.py).
    """
    def __init__(self):
        #Set default value of parameters.
        
        self._heroku = {'api_key': '',
                       'app_name': ''
        }
        self._newrelic = {'api_key': '',
                          'account_id': '',
                         'app_id': ''
        }
        self._autoscale_settings = {'min_dynos': 1,
                                   'max_dynos': 10,
                                   'apdex_low': 0.5,
                                   'apdex_high': 0.8,
                                   'check_frequency': 5
        }
    
    def setHerokuAPIKey(self, heroku_api_key):
        """Set the Heroku API Key
        
        Argument:
        - heroku_api_key: The Heroku API Key
        """
        self._heroku['api_key'] = heroku_api_key
        
    def getHerokuAPIKey(self):
        """Get the Heroku API Key
        
        Return: The Heroku API Key
        """
        return self._heroku['api_key']
    
    def setHerokuAppName(self, heroku_app_name):
        """Set the Heroku App name
        
        Argument:
        - heroku_app_name: The Heroku App name
        """
        self._heroku['app_name'] = heroku_app_name
        
    def getHerokuAppName(self):
        """Get the Heroku Application name
        
        Return: The Heroku Application name
        """
        return self._heroku['app_name']
    
    def setNewRelicAPIKey(self, newrelic_api_key):
        """Set the NewRelic API Key
        
        Argument:
        - newrelic_api_key: The NewRelic API Key
        """
        self._newrelic['api_key'] = newrelic_api_key
    
    def getNewRelicAPIKey(self):
        """Get the NewRelic API Key
        
        Return: The NewRelic API Key
        """
        return self._newrelic['api_key']
    
    def setNewRelicAccountId(self, newrelic_account_id):
        """Set the NewRelic Accound ID
        
        Argument:
        - newrelic_account_id: The NewRelic Accound ID
        """
        self._newrelic['account_id'] = newrelic_account_id
    
    def getNewRelicAccountId(self):
        """Get the NewRelic Account ID
        
        Return: The NewRelic Account ID
        """
        return self._newrelic['account_id']
    
    def setNewRelicAppId(self, newrelic_app_id):
        """Set the NewRelic App ID
        
        Argument:
        - newrelic_app_id: The NewRelic App ID
        """
        self._newrelic['app_id'] = newrelic_app_id
        
    def getNewRelicAppId(self):
        """Get the NewRelic App ID
        
        Return: The NewRelic App ID
        """
        return self._newrelic['app_id']
    
    def setMinDynos(self, min_dynos):
        """Set the minimun number of dynos
        
        The autoscale app will not scale down the Heroku app under that number of dynos
        
        Argument:
        - min_dynos: The minimun number of dynos
        """
        if(min_dynos < 1):
            raise ConfigException("You have to set at least 1 dyno minimum (you indicate {0})".format(min_dynos))
        self._autoscale_settings['min_dynos'] = min_dynos
    
    def getMinDynos(self):
        """Get the minimun number of dynos
        
        The autoscale app will not scale down the Heroku app under that number of dynos
        
        Return: The minimun number of dynos
        """
        return self._autoscale_settings['min_dynos']
    
    def setMaxDynos(self, max_dynos):
        """Set the maximum number of dynos
        
        The autoscale app will not scale up the Heroku app over that number of dynos
        
        Argument:
        - max_dynos: The maximum number of dynos
        """
        self._autoscale_settings['max_dynos'] = max_dynos
        
    def getMaxDynos(self):
        """Get the maximum number of dynos
        
        The autoscale app will not scale up the Heroku app over that number of dynos
        
        Return: The maximum number of dynos
        """
        return self._autoscale_settings['max_dynos']
    
    def setApdexLowScore(self, apdex_low_score):
        """Set the Apdex Low Score
        
        If the measured apdex score is below this number, the Heroku app will be scaled up.
        
        Argument:
        - apdex_low_score: The NewRelic Apdex Low Score
        """
        if(isinstance(apdex_low_score, float) and apdex_low_score >= 0 and apdex_low_score <= 1):
            self._autoscale_settings['apdex_low'] = apdex_low_score
        else:
            raise ConfigException("Apdex low score must be a float value, between 0 and 1 (you indicate {0})".format(apdex_low_score))
    
    def getApdexLowScore(self):
        """Get the NewRelic Apdex Low Score
        
        If the measured apdex score is below this number, the Heroku app will be scaled up.
        
        Return: The NewRelic Apdex Low Score
        """
        return self._autoscale_settings['apdex_low']
        
    def setApdexHighScore(self, apdex_high_score):
        """Set the Apdex High Score
        
        If the measured apdex score is over this number, the Heroku app will be scaled down.
        
        Argument:
        - apdex_high_score: The NewRelic Apdex High Score
        """
        if(isinstance(apdex_high_score, float) and apdex_high_score >= 0 and apdex_high_score <= 1):
            self._autoscale_settings['apdex_high'] = apdex_high_score
        else:
            raise ConfigException("Apdex high score must be a float value, between 0 and 1 (you indicate {0})".format(apdex_high_score))
    
    def getApdexHighScore(self):
        """Get the NewRelic Apdex High Score
        
        If the measured apdex score is over this number, the Heroku app will be scaled down.
        
        Return: The NewRelic Apdex High Score
        """
        return self._autoscale_settings['apdex_high']
    
    def setCheckFrequency(self, check_frequency):
        """Set the check frequency (in minutes)
        
        Argument:
        - check_frequency: The check frequency
        """
        if(check_frequency < 1):
            raise ConfigException("The check frequency must be at least 1 minute (you indicate {0})".format(check_frequency))
        self._autoscale_settings['check_frequency'] = check_frequency
        
    def getCheckFrequency(self):
        """Get the check frequency (in minutes)
        
        Return: The check frequency
        """
        return self._autoscale_settings['check_frequency']